apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor-clients
  namespace: snus
spec:
  replicas: 5
  selector:
    matchLabels:
      app: sensor-client
  template:
    metadata:
      labels:
        app: sensor-client
    spec:
      containers:
        - name: sensor-client
          image: snus-sensor-client:local
          imagePullPolicy: IfNotPresent
          env:
            - name: SERVER_URL
              value: http://ingestion:8080
            - name: DATA_QUALITY
              value: Good
            - name: THRESHOLD_P1
              value: "80"
            - name: THRESHOLD_P2
              value: "100"
            - name: THRESHOLD_P3
              value: "110"
            - name: SENSOR_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
