// <auto-generated />
using System;
using DistributedObservationSystem.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DistributedObservationSystem.Persistence.Migrations
{
    [DbContext(typeof(ObservationDbContext))]
    partial class ObservationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DistributedObservationSystem.Persistence.Entities.AlarmEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("MeasuredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("SensorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Value")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("SensorId", "MeasuredAtUtc");

                    b.ToTable("AlarmEvents");
                });

            modelBuilder.Entity("DistributedObservationSystem.Persistence.Entities.ConsensusReading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Value")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTimeOffset>("WindowEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("WindowStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("WindowStartUtc");

                    b.ToTable("ConsensusReadings");
                });

            modelBuilder.Entity("DistributedObservationSystem.Persistence.Entities.Sensor", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("BlockedUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DataQuality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastMessageAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("LastMessageId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("MaximumTemperature")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("MinimumTemperature")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Sensors");
                });

            modelBuilder.Entity("DistributedObservationSystem.Persistence.Entities.SensorReading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AlarmPriority")
                        .HasColumnType("integer");

                    b.Property<bool>("IsConsensus")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("MeasuredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SensorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Value")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("MeasuredAtUtc");

                    b.HasIndex("SensorId", "MeasuredAtUtc");

                    b.ToTable("SensorReadings");
                });
#pragma warning restore 612, 618
        }
    }
}
